// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png"
  ]
};

// ../../../../AppData/Local/nvm/v22.20.0/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "C:\\Users\\monag\\_Projects\\starspace\\Dashboard\\dashboard\\.wrangler\\tmp\\pages-vVrAJu\\bundledWorker-0.5899413989274955.mjs";
import { isRoutingRuleMatch } from "C:\\Users\\monag\\AppData\\Local\\nvm\\v22.20.0\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "C:\\Users\\monag\\_Projects\\starspace\\Dashboard\\dashboard\\.wrangler\\tmp\\pages-vVrAJu\\bundledWorker-0.5899413989274955.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=tk2w8ysmz4s.js.map
